


LLAMA3_8B_EXPERIMENT_CONFIGS = {
    "ga_lora": {
        "stage": "ga",
        "dataset_suffix": "Positive",
        "output_dir": "./saves/lora/llama3_8b_instruct/ga",
        "log_dir": "./logs/lora/llama3_8b_instruct/ga",
        "output_result_dir": "./results/lora/llama3_8b_instruct/ga",
        "eval_dataset_dir": "./data/ORT/Target/",
        "batch_size": 8,
        "learning_rate": "2e-5",
        "epochs": 5.0,
        "grad_accum_steps": 2,
        "extra_args": [],
        "gpu": "0,1"
    },
    "npo_lora": {
        "stage": "npo",
        "dataset_suffix": "Positive",
        "output_dir": "./saves/lora/llama3_8b_instruct/npo_lora",
        "log_dir": "./logs/lora/llama3_8b_instruct/npo_lora",
        "output_result_dir": "./results/lora/llama3_8b_instruct/npo_lora",
        "eval_dataset_dir": "./data/ORT/Target/",
        "batch_size": 8,
        "learning_rate": "5e-5",  
        "epochs": 5.0,
        "grad_accum_steps": 2,
        "extra_args": ["--dpo_beta", "0.0275", "--save_model"],
        "gpu": None  
    },
    "rt_lora": {
        "stage": "rt",
        "dataset_suffix": "Reject",
        "output_dir": "./saves/lora/llama3_8b_instruct/rt_lora",
        "log_dir": "./logs/lora/llama3_8b_instruct/rt_lora",
        "output_result_dir": "./results/lora/llama3_8b_instruct/rt_lora",
        "eval_dataset_dir": "./data/ORT/Target/",
        "batch_size": 8,
        "learning_rate": "5e-5",
        "epochs": 5.0,
        "grad_accum_steps": 1,
        "extra_args": [""],
        "gpu": None  
    },
    "cft_lora": {
        "stage": "cft",
        "dataset_suffix": "Counterfact",
        "output_dir": "./saves/lora/llama3_8b_instruct/cft_lora",
        "log_dir": "./logs/lora/llama3_8b_instruct/cft_lora",
        "output_result_dir": "./results/lora/llama3_8b_instruct/cft_lora",
        "eval_dataset_dir": "./data/ORT/Target/",
        "batch_size": 8,
        "learning_rate": "3e-5",
        "epochs": 5.0,
        "grad_accum_steps": 1,
        "extra_args": [""],
        "gpu": None  
    },
    "dpo_lora_reject": {
        "stage": "dpo",
        "dataset_suffix": "Pair_Reject",
        "output_dir": "./saves/lora/llama3_8b_instruct/dpo_lora_reject",
        "log_dir": "./logs/lora/llama3_8b_instruct/dpo_lora_reject",
        "output_result_dir": "./results/lora/llama3_8b_instruct/dpo_lora_reject",
        "eval_dataset_dir": "./data/ORT/Target/",
        "batch_size": 4,
        "learning_rate": "1e-4",  
        "epochs": 5.0,
        "grad_accum_steps": 2,
        "extra_args": ["--dpo_ftx", "0.0", "--save_model"],
        "gpu": "0,1"
    },
    "original": {
        "stage": "ga",
        "dataset_suffix": "Positive",
        "output_dir": "./saves/lora/llama3_8b_instruct/original",
        "log_dir": "./logs/lora/llama3_8b_instruct/original",
        "output_result_dir": "./results/lora/llama3_8b_instruct/original",
        "eval_dataset_dir": "./data/ORT/Target/",
        "batch_size": 8,
        "learning_rate": "1e-5",
        "epochs": 5.0,
        "grad_accum_steps": 1,
        "extra_args": [],
        "gpu": None,  
        "skip_train": True  
    },
    "rocr": {
        "stage": "rocr",  
        "dataset_suffix": "Positive",  
        "output_dir": "./saves/lora/llama3_8b_instruct/rocr",
        "log_dir": "./logs/lora/llama3_8b_instruct/rocr",
        "output_result_dir": "./results/lora/llama3_8b_instruct/rocr",
        "eval_dataset_dir": "./data/ORT/Target/",
        "batch_size": 1,  
        "learning_rate": "0",  
        "epochs": 0,  
        "grad_accum_steps": 1,
        "extra_args": ["--save_model"],  
        "gpu": "0",  
    }
} 